#!/bin/bash

#find real script directory
#DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

echo clear
echo
echo _________________________
echo installing all stuff:
echo git: \(probably already installed\)
sudo apt --assume-yes install git
echo gitk:
sudo apt --assume-yes install gitk
echo python3:
sudo apt --assume-yes install python3
echo pip for the python3:
sudo apt --assume-yes install python3-pip
echo curl:
sudo apt --assume-yes install curl
echo wine
sudo apt --assume-yes install wine-stable
echo install cmake & build essental packages for debian and python
sudo apt --assume-yes install build-essential cmake python3-dev


echo _________________________
echo installing environment and tools:
echo regolith i3 tiling windows manager:
sudo add-apt-repository -y ppa:kgilmer/regolith-stable
sudo apt --assume-yes install regolith-desktop
echo tldr:
sudo apt --assume-yes install tldr
echo htop:
sudo apt --assume-yes install htop
echo ranger:
sudo apt --assume-yes install ranger
echo zsh:
sudo apt --assume-yes install zsh


echo _________________________
echo documentation like stuff:
echo doxygen
sudo apt --assume-yes install doxygen
echo lcov for a doxygen comments coverage
sudo apt --assume-yes install lcov
echo coverxygen for a doxygen comments coverage
pip3 install coverxygen
echo graphviz for a doxygen
sudo apt --assume-yes install graphviz
echo plantUML
sudo apt --assume-yes install plantuml


# shell like stuff
echo oh-my-zsh:
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" "" --unattended
echo PowerLevel9k plugin for zsh:
git clone https://github.com/bhilburn/powerlevel9k.git ~/.oh-my-zsh/custom/themes/powerlevel9k



echo _________________________
echo vim
sudo apt --assume-yes install vim
sudo apt --assume-yes install vim-gtk3
echo silversearcher-ag search engine for vim
sudo apt --assume-yes install silversearcher-ag
echo install Excuberant tags:
sudo apt --assume-yes install exuberant-ctags





# VIM like stuff
echo _________________________
echo install vim plugins
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
echo create backup and swap directory for vim
mkdir -p ~/.vim/backup
mkdir -p ~/.vim/swap
echo _________________________
echo open vim, update all plugins and quit vim:
sleep 1
vim -c BundleUpdate -c q -c q

#install You Complete Me the Vim plugin
echo _________________________
echo install clang-completer for YCM
cd ~/.vim/bundle/YouCompleteMe
python3 install.py --clang-completer

echo compile and install Bear for YCM and vim
git clone https://github.com/rizsotto/Bear.git ~/Bear_Source_Tmp/
cd ~/Bear_Source_Tmp
cmake ~/Bear_Source_Tmp
make all
sudo make install
make check
sudo make package
sudo rm -rdf ~/Bear_Source_Tmp/


echo _________________________
echo set zsh as default shell
chsh -s $(which zsh)
echo
echo
echo ___________________________________________
echo "===                 DONE                ==="
echo
echo Your Vim is already installed and configured
echo

echo TODO:
echo - install font for vim
echo - install GVim
