#!/bin/bash

#find real script directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
#make a soft links of yours dotfile
echo
echo creating symbolic links from $DIR to system dotfiles in ~/


echo "install settings for a:"
select yn in "Work" "Private"; do
    case $yn in
        Work ) ln --symbolic --interactive $DIR/.gitconfig_work ~/.gitconfig; break;;
        Private ) ln --symbolic --interactive $DIR/.gitconfig_private ~/.gitconfig; break;
    esac
done


ln --symbolic --interactive $DIR/.vimrc  ~/.vimrc
