#!/bin/bash

#find real script directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
#make a soft links of yours dotfile

echo ____________________
echo creating symbolic links from $DIR to system dotfiles in ~/
echo ABORT script if you wanted to save your setting first!
read -r -p "..." tmp


ln --symbolic --force $DIR/.vimrc  ~/.vimrc

echo "install settings for a:"
select yn in "Work" "Private"; do
    case $yn in
        Work ) ln --symbolic --force $DIR/.gitconfig_work ~/.gitconfig; break;;
        Private ) ln --symbolic --force $DIR/.gitconfig_private ~/.gitconfig; exit;
    esac
done


read -r -p "write your email:" mail
git config --global user.email $mail
read -r -p "write your name:" name
git config --global user.name "$name"
